version: '3.4'
services: 
    ms-sql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "suPerSecret5Assword"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
    airport-web:
        build:
            dockerfile: Web/Dockerfile
            context: .
        environment:
            DbServer: tcp:ms-sql
            DbPort: "1433"
            DbUser: "sa"
            DbPassword: "suPerSecret5Assword"
            Database: "AirlinesApplicationDb"
            IdentityDatabase: "AirlinesIdentityDb"
        ports:
            - "80:80"
        depends_on:
            - ms-sql